server:
  port: 8001
spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq: #rabbitmq相关配置
    host: ip
    port: 5672
    username: deltaqin
    password: deltaqin
    virtual-host: /
  # 加载所有的端点/默认只加载了 info / health
  boot:
    admin:
      client:
#        instance:
        url: http://localhost:8041
        username: deltaqin
        password: deltaqin
  info:
    app:
      name: ${spring.application.name}
      description: "@project.description@"
      version: "@project.version@"
  shardingsphere:
    datasource:
      names: m1,m2
#      配置数据源
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://ip:3306/heterogeneous1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: QZT1234567890
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://ip:3307/heterogeneous2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: QZT1234567890

    sharding:
      #      分库策略（水平）
      default-database-strategy:
        inline:
          sharding-column: cid
          algorithm-expression: m$->{cid % 2 + 1}
      #      分表策略（水平）
      tables:
        #        sys_admin分表策略
        #        数据结点包括:m1.sys_admin_1,m1.sys_admin_2,m2.sys_admin_1,m2.sys_admin_2,
        sys_admin:
          actual-data-nodes: m$->{1..2}.sys_admin_$->{1..2}
          table-strategy:
            inline:
              #              分片策略包括分片键和分片算法
              sharding-column: id
              algorithm-expression: sys_admin_$->{id % 2 + 1}
          #          指定表的主键，且生成策略为SNOWFLAKE
          key-generator:
            type: SNOWFLAKE
            column: id
        sys_admin_login_log:
          actual-data-nodes: m$->{1..2}.sys_admin_login_log
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: sys_admin_login_log
          key-generator:
            type: SNOWFLAKE
            column: id
      #     指定公共表
      broadcast-tables[0]: sys_admin_role_relation
      broadcast-tables[1]: sys_remote_database_type
      broadcast-tables[2]: sys_remote_panal_type
      broadcast-tables[3]: sys_resource
      broadcast-tables[4]: sys_role
      broadcast-tables[5]: sys_role_resource_relation
      broadcast-tables[6]: sys_company

    props:
      sql:
        show: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 客户端的所有监控端点都暴露给SBA服务端；
  endpoint:
    health:
      show-details: ALWAYS  # 总是展示详细的健康信息。

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

redis:
  database: sys
  key:
    admin: 'sys:user'
  expire:
    common: 86400 # 24小时
feign:
  okhttp:
    enabled: true
#ribbon:
#  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
